# golangci-lint v2 configuration
version: "2"

run:
  timeout: 5m

output:
  formats:
    colored-line-number: {}
  print-issued-lines: true
  print-linter-name: true

linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - copyloopvar
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    govet:
      enable:
        - shadow
    gocyclo:
      min-complexity: 30
    dupl:
      threshold: 100
    goconst:
      min-len: 3
      min-occurrences: 3
    misspell:
      locale: US
    lll:
      line-length: 120
    gocritic:
      enabled-tags:
        - performance
        - style
        - experimental
      disabled-checks:
        - wrapperFunc
        - commentedOutCode
    godox:
      keywords:
        - TODO
        - BUG
        - FIXME
        - NOTE
        - HACK

issues:
  exclude-dirs:
    - vendor
  exclude:
    - "should have a package comment"
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - path: example.*\.go
      linters:
        - errcheck
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/SimonWaldherr/tinySQL
