// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.0
// source: tinysql.proto

package serverpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TinySQL_Exec_FullMethodName            = "/tinysql.TinySQL/Exec"
	TinySQL_Query_FullMethodName           = "/tinysql.TinySQL/Query"
	TinySQL_QueryStream_FullMethodName     = "/tinysql.TinySQL/QueryStream"
	TinySQL_Bootstrap_FullMethodName       = "/tinysql.TinySQL/Bootstrap"
	TinySQL_GetChangesSince_FullMethodName = "/tinysql.TinySQL/GetChangesSince"
	TinySQL_GetChanges_FullMethodName      = "/tinysql.TinySQL/GetChanges"
)

// TinySQLClient is the client API for TinySQL service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TinySQLClient interface {
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	QueryStream(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryStreamResponse], error)
	Bootstrap(ctx context.Context, in *BootstrapRequest, opts ...grpc.CallOption) (*BootstrapResponse, error)
	GetChangesSince(ctx context.Context, in *GetChangesSinceRequest, opts ...grpc.CallOption) (*GetChangesSinceResponse, error)
	GetChanges(ctx context.Context, in *GetChangesSinceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetChangesSinceResponse], error)
}

type tinySQLClient struct {
	cc grpc.ClientConnInterface
}

func NewTinySQLClient(cc grpc.ClientConnInterface) TinySQLClient {
	return &tinySQLClient{cc}
}

func (c *tinySQLClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecResponse)
	err := c.cc.Invoke(ctx, TinySQL_Exec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tinySQLClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, TinySQL_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tinySQLClient) QueryStream(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TinySQL_ServiceDesc.Streams[0], TinySQL_QueryStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QueryRequest, QueryStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TinySQL_QueryStreamClient = grpc.ServerStreamingClient[QueryStreamResponse]

func (c *tinySQLClient) Bootstrap(ctx context.Context, in *BootstrapRequest, opts ...grpc.CallOption) (*BootstrapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BootstrapResponse)
	err := c.cc.Invoke(ctx, TinySQL_Bootstrap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tinySQLClient) GetChangesSince(ctx context.Context, in *GetChangesSinceRequest, opts ...grpc.CallOption) (*GetChangesSinceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChangesSinceResponse)
	err := c.cc.Invoke(ctx, TinySQL_GetChangesSince_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tinySQLClient) GetChanges(ctx context.Context, in *GetChangesSinceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetChangesSinceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TinySQL_ServiceDesc.Streams[1], TinySQL_GetChanges_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetChangesSinceRequest, GetChangesSinceResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TinySQL_GetChangesClient = grpc.ServerStreamingClient[GetChangesSinceResponse]

// TinySQLServer is the server API for TinySQL service.
// All implementations must embed UnimplementedTinySQLServer
// for forward compatibility.
type TinySQLServer interface {
	Exec(context.Context, *ExecRequest) (*ExecResponse, error)
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	QueryStream(*QueryRequest, grpc.ServerStreamingServer[QueryStreamResponse]) error
	Bootstrap(context.Context, *BootstrapRequest) (*BootstrapResponse, error)
	GetChangesSince(context.Context, *GetChangesSinceRequest) (*GetChangesSinceResponse, error)
	GetChanges(*GetChangesSinceRequest, grpc.ServerStreamingServer[GetChangesSinceResponse]) error
	mustEmbedUnimplementedTinySQLServer()
}

// UnimplementedTinySQLServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTinySQLServer struct{}

func (UnimplementedTinySQLServer) Exec(context.Context, *ExecRequest) (*ExecResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedTinySQLServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedTinySQLServer) QueryStream(*QueryRequest, grpc.ServerStreamingServer[QueryStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method QueryStream not implemented")
}
func (UnimplementedTinySQLServer) Bootstrap(context.Context, *BootstrapRequest) (*BootstrapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bootstrap not implemented")
}
func (UnimplementedTinySQLServer) GetChangesSince(context.Context, *GetChangesSinceRequest) (*GetChangesSinceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChangesSince not implemented")
}
func (UnimplementedTinySQLServer) GetChanges(*GetChangesSinceRequest, grpc.ServerStreamingServer[GetChangesSinceResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetChanges not implemented")
}
func (UnimplementedTinySQLServer) mustEmbedUnimplementedTinySQLServer() {}
func (UnimplementedTinySQLServer) testEmbeddedByValue()                 {}

// UnsafeTinySQLServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TinySQLServer will
// result in compilation errors.
type UnsafeTinySQLServer interface {
	mustEmbedUnimplementedTinySQLServer()
}

func RegisterTinySQLServer(s grpc.ServiceRegistrar, srv TinySQLServer) {
	// If the following call pancis, it indicates UnimplementedTinySQLServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TinySQL_ServiceDesc, srv)
}

func _TinySQL_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TinySQLServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TinySQL_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TinySQLServer).Exec(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TinySQL_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TinySQLServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TinySQL_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TinySQLServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TinySQL_QueryStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TinySQLServer).QueryStream(m, &grpc.GenericServerStream[QueryRequest, QueryStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TinySQL_QueryStreamServer = grpc.ServerStreamingServer[QueryStreamResponse]

func _TinySQL_Bootstrap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BootstrapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TinySQLServer).Bootstrap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TinySQL_Bootstrap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TinySQLServer).Bootstrap(ctx, req.(*BootstrapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TinySQL_GetChangesSince_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChangesSinceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TinySQLServer).GetChangesSince(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TinySQL_GetChangesSince_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TinySQLServer).GetChangesSince(ctx, req.(*GetChangesSinceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TinySQL_GetChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetChangesSinceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TinySQLServer).GetChanges(m, &grpc.GenericServerStream[GetChangesSinceRequest, GetChangesSinceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TinySQL_GetChangesServer = grpc.ServerStreamingServer[GetChangesSinceResponse]

// TinySQL_ServiceDesc is the grpc.ServiceDesc for TinySQL service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TinySQL_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tinysql.TinySQL",
	HandlerType: (*TinySQLServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Exec",
			Handler:    _TinySQL_Exec_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _TinySQL_Query_Handler,
		},
		{
			MethodName: "Bootstrap",
			Handler:    _TinySQL_Bootstrap_Handler,
		},
		{
			MethodName: "GetChangesSince",
			Handler:    _TinySQL_GetChangesSince_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "QueryStream",
			Handler:       _TinySQL_QueryStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetChanges",
			Handler:       _TinySQL_GetChanges_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tinysql.proto",
}
