name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download deps
        run: go mod download

      - name: Run unit tests (no cache)
        run: go test ./... -count=1

      - name: Run coverage
        run: go test -coverprofile=coverage.out ./...

      - name: Summarize coverage
        run: |
          go tool cover -func=coverage.out -o coverage.txt
          tail -1 coverage.txt >> $GITHUB_STEP_SUMMARY